# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'aboutUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_qtUCAbout(object):
    def setupUi(self, qtUCAbout):
        qtUCAbout.setObjectName("qtUCAbout")
        qtUCAbout.setWindowModality(QtCore.Qt.ApplicationModal)
        qtUCAbout.resize(320, 278)
        qtUCAbout.setModal(True)
        self.buttonBox = QtWidgets.QDialogButtonBox(qtUCAbout)
        self.buttonBox.setGeometry(QtCore.QRect(10, 240, 301, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(qtUCAbout)
        self.buttonBox.accepted.connect(qtUCAbout.accept)
        self.buttonBox.rejected.connect(qtUCAbout.reject)
        QtCore.QMetaObject.connectSlotsByName(qtUCAbout)

    def retranslateUi(self, qtUCAbout):
        _translate = QtCore.QCoreApplication.translate
        qtUCAbout.setWindowTitle(_translate("qtUCAbout", "About qtUC"))
