# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'notificationUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_notification(object):
    def setupUi(self, notification):
        notification.setObjectName("notification")
        notification.resize(294, 64)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(notification.sizePolicy().hasHeightForWidth())
        notification.setSizePolicy(sizePolicy)
        self.msgLabel = QtWidgets.QLabel(notification)
        self.msgLabel.setGeometry(QtCore.QRect(10, 22, 270, 31))
        self.msgLabel.setWordWrap(True)
        self.msgLabel.setObjectName("msgLabel")
        self.titleLabel = QtWidgets.QLabel(notification)
        self.titleLabel.setGeometry(QtCore.QRect(10, 0, 270, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")

        self.retranslateUi(notification)
        QtCore.QMetaObject.connectSlotsByName(notification)

    def retranslateUi(self, notification):
        _translate = QtCore.QCoreApplication.translate
        notification.setWindowTitle(_translate("notification", "Form"))
        self.msgLabel.setText(_translate("notification", "msgLabel"))
        self.titleLabel.setText(_translate("notification", "titleLabel"))
