# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tgDlgUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tgDlg(object):
    def setupUi(self, tgDlg):
        tgDlg.setObjectName("tgDlg")
        tgDlg.resize(226, 142)
        tgDlg.setModal(True)
        self.horizontalLayoutWidget = QtWidgets.QWidget(tgDlg)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 211, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.editTgrp = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.editTgrp.setObjectName("editTgrp")
        self.horizontalLayout.addWidget(self.editTgrp)
        self.lbTSlot = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.lbTSlot.setObjectName("lbTSlot")
        self.horizontalLayout.addWidget(self.lbTSlot)
        self.sbTSlot = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.sbTSlot.setMinimum(1)
        self.sbTSlot.setMaximum(2)
        self.sbTSlot.setProperty("value", 2)
        self.sbTSlot.setObjectName("sbTSlot")
        self.horizontalLayout.addWidget(self.sbTSlot)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(tgDlg)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 110, 221, 32))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btnCancel = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.btnCancel.setDefault(False)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout_2.addWidget(self.btnCancel)
        self.selTgBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.selTgBtn.setDefault(True)
        self.selTgBtn.setObjectName("selTgBtn")
        self.horizontalLayout_2.addWidget(self.selTgBtn)
        self.cbMacros = QtWidgets.QComboBox(tgDlg)
        self.cbMacros.setGeometry(QtCore.QRect(10, 70, 211, 26))
        self.cbMacros.setObjectName("cbMacros")
        self.cbPvtCall = QtWidgets.QCheckBox(tgDlg)
        self.cbPvtCall.setGeometry(QtCore.QRect(116, 44, 100, 20))
        self.cbPvtCall.setObjectName("cbPvtCall")
        self.label_2 = QtWidgets.QLabel(tgDlg)
        self.label_2.setGeometry(QtCore.QRect(16, 50, 60, 16))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(tgDlg)
        QtCore.QMetaObject.connectSlotsByName(tgDlg)

    def retranslateUi(self, tgDlg):
        _translate = QtCore.QCoreApplication.translate
        tgDlg.setWindowTitle(_translate("tgDlg", "Talk Groups"))
        self.label.setText(_translate("tgDlg", "TG"))
        self.lbTSlot.setText(_translate("tgDlg", "TS"))
        self.btnCancel.setText(_translate("tgDlg", "Cancel"))
        self.selTgBtn.setText(_translate("tgDlg", "Select"))
        self.cbPvtCall.setText(_translate("tgDlg", "Private Call"))
        self.label_2.setText(_translate("tgDlg", "Macro"))
