# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tgEditDlgUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tgEditDlg(object):
    def setupUi(self, tgEditDlg):
        tgEditDlg.setObjectName("tgEditDlg")
        tgEditDlg.resize(275, 235)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(tgEditDlg.sizePolicy().hasHeightForWidth())
        tgEditDlg.setSizePolicy(sizePolicy)
        tgEditDlg.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        tgEditDlg.setFont(font)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(tgEditDlg)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.plTextEdit = QtWidgets.QPlainTextEdit(tgEditDlg)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.plTextEdit.setFont(font)
        self.plTextEdit.setObjectName("plTextEdit")
        self.verticalLayout.addWidget(self.plTextEdit)
        self.buttonBox = QtWidgets.QDialogButtonBox(tgEditDlg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(tgEditDlg)
        QtCore.QMetaObject.connectSlotsByName(tgEditDlg)

    def retranslateUi(self, tgEditDlg):
        _translate = QtCore.QCoreApplication.translate
        tgEditDlg.setWindowTitle(_translate("tgEditDlg", "Talk Groups"))
